In [1]:
import geopandas as gpd
from keplergl import KeplerGl

In [2]:
gdf = gpd.read_file(r"C:\Users\bruno\Documents\J3Q3-4 BEP\repositories\FINALDATASET3.shp")
gdf

,name_x,fclass,osm_id,long,latt,cluster,C_PTS,D_C_PTS,C_Super,D_C_Super,C_DoctorsI,D_C_Doctor,C_SchoolsI,D_C_School,C_SportID,D_C_Sport,accs,geometry
0,The Hague Tower,building,37774391,4.324224,52.071575,3603,1301378,107.161512,170,397.025030,12,644.307493,78,1093.290909,92,351.857639,1,POINT (4.32422 52.07158)
1,None,building,267117842,4.324910,52.071850,3603,1301378,107.161512,170,397.025030,12,644.307493,78,1093.290909,92,351.857639,1,POINT (4.32491 52.07185)
2,None,building,58350937,4.319504,52.019770,1403,16402,1401.525367,59,2545.583465,3,2830.766890,101,3064.414074,13,2781.176538,0,POINT (4.31950 52.01977)
3,None,building,253797461,4.320369,52.019398,1403,16402,1401.525367,59,2545.583465,3,2830.766890,101,3064.414074,13,2781.176538,0,POINT (4.32037 52.01940)
4,None,building,427468640,4.321300,52.018973,1403,16402,1401.525367,59,2545.583465,3,2830.766890,101,3064.414074,13,2781.176538,0,POINT (4.32130 52.01897)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93480,None,building,766622131,4.382658,52.054053,3714,651931,435.366264,67,1704.349670,29,1777.164385,9,1302.511442,6,1596.647441,4,POINT (4.38266 52.05405)
93481,None,building,697411648,4.381724,52.054196,600,651931,628.828303,67,1897.811709,29,1970.626425,9,1495.973482,6,1790.109481,4,POINT (4.38172 52.05420)
93482,None,building,766622106,4.382214,52.054351,600,651931,628.828303,67,1897.811709,29,1970.626425,9,1495.973482,6,1790.109481,4,POINT (4.38221 52.05435)
93483,None,building,745899409,4.218895,52.041474,4934,1547770,1639.160926,163,2204.908802,65,4893.801925,90,4589.109529,47,2636.794572,0,POINT (4.21889 52.04147)
93484,None,building,745899513,4.218672,52.041785,4934,1547770,1639.160926,163,2204.908802,65,4893.801925,90,4589.109529,47,2636.794572,0,POINT (4.21867 52.04179)

In [11]:
config = {
  "version": "v1",
  "config": {
    "visState": {
      "filters": [],
      "layers": [
        {
          "id": "65n92e",
          "type": "point",
          "config": {
            "dataId": "data_2",
            "label": "data_2",
            "color": [
              255,
              153,
              31
            ],
            "columns": {
              "lat": "latt",
              "lng": "long",
              "altitude": "accs"
            },
            "isVisible": True,
            "visConfig": {
              "radius": 4,
              "fixedRadius": False,
              "opacity": 0.8,
              "outline": False,
              "thickness": 0.5,
              "strokeColor": [
                225,
                49,
                106
              ],
              "colorRange": {
                "name": "UberPool 6",
                "type": "diverging",
                "category": "Uber",
                "colors": [
                  "#213E9A",
                  "#551EAD",
                  "#C019BD",
                  "#D31256",
                  "#E6470A",
                  "#F9E200"
                ]
              },
              "strokeColorRange": {
                "name": "UberPool 6",
                "type": "diverging",
                "category": "Uber",
                "colors": [
                  "#213E9A",
                  "#551EAD",
                  "#C019BD",
                  "#D31256",
                  "#E6470A",
                  "#F9E200"
                ]
              },
              "radiusRange": [
                0,
                50
              ],
              "filled": True
            },
            "hidden": False,
            "textLabel": []
          },
          "visualChannels": {
            "colorField": {
              "name": "accs",
              "type": "integer"
            },
            "colorScale": "quantize",
            "strokeColorField": {
              "name": "accs",
              "type": "integer"
            },
            "strokeColorScale": "quantize",
            "sizeField": None,
            "sizeScale": "linear"
          }
        }
      ],
      "interactionConfig": {
        "tooltip": {
          "fieldsToShow": {
            "data_2": [
              "D_C_PTS",
              "D_C_Super",
              "D_C_Doctor",
              "D_C_School",
              "D_C_Sport",
              "accs"
            ]
          },
          "enabled": True
        },
        "brush": {
          "size": 0.5,
          "enabled": False
        },
        "geocoder": {
          "enabled": False
        },
        "coordinate": {
          "enabled": False
        }
      },
      "layerBlending": "normal",
      "splitMaps": [],
      "animationConfig": {
        "currentTime": None,
        "speed": 1
      }
    },
    "mapState": {
      "bearing": 0,
      "dragRotate": False,
      "latitude": 52.06007990791819,
      "longitude": 4.307741205732435,
      "pitch": 0,
      "zoom": 11.66246341000922,
      "isSplit": False
    },
    "mapStyle": {
      "styleType": "dark",
      "topLayerGroups": {},
      "visibleLayerGroups": {
        "label": True,
        "road": True,
        "border": False,
        "building": True,
        "water": True,
        "land": True,
        "3d building": False
      },
      "threeDBuildingColor": [
        9.665468314072013,
        17.18305478057247,
        31.1442867897876
      ],
      "mapStyles": {}
    }
  }
}

In [12]:
map_1 = KeplerGl()
map_1.add_data(data=gdf, name='data_2')
map_1.config = config
map_1

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [{'id': '65n92e', 'type': 'â€¦

In [13]:
map_1.save_to_html(data={'data_2': gdf}, config=config, file_name='final_map.html')

Map saved to final_map.html!